
// This file has been generated by the GUI designer. Do not modify.
namespace GatewayRAMTools
{
	public partial class PartitionWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label lblFName;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treePartition;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Entry txtRAM;
		
		private global::Gtk.Entry txtFile;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button btnExport;
		
		private global::Gtk.Button btnPartClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GatewayRAMTools.PartitionWindow
			this.Name = "GatewayRAMTools.PartitionWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("PartitionWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child GatewayRAMTools.PartitionWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblFName = new global::Gtk.Label ();
			this.lblFName.Name = "lblFName";
			this.lblFName.LabelProp = global::Mono.Unix.Catalog.GetString ("{Filename}");
			this.vbox2.Add (this.lblFName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblFName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(3));
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(3));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treePartition = new global::Gtk.TreeView ();
			this.treePartition.CanFocus = true;
			this.treePartition.Name = "treePartition";
			this.GtkScrolledWindow.Add (this.treePartition);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("RAM Offset");
			this.hbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("File Offset");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w5.Position = 1;
			w5.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.hbox3.BorderWidth = ((uint)(3));
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtRAM = new global::Gtk.Entry ();
			this.txtRAM.CanFocus = true;
			this.txtRAM.Name = "txtRAM";
			this.txtRAM.Text = global::Mono.Unix.Catalog.GetString ("00000000");
			this.txtRAM.IsEditable = true;
			this.txtRAM.MaxLength = 8;
			this.txtRAM.InvisibleChar = '●';
			this.hbox3.Add (this.txtRAM);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtRAM]));
			w7.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtFile = new global::Gtk.Entry ();
			this.txtFile.CanFocus = true;
			this.txtFile.Name = "txtFile";
			this.txtFile.Text = global::Mono.Unix.Catalog.GetString ("00000000");
			this.txtFile.IsEditable = true;
			this.txtFile.MaxLength = 8;
			this.txtFile.InvisibleChar = '●';
			this.hbox3.Add (this.txtFile);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtFile]));
			w8.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(3));
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnExport = new global::Gtk.Button ();
			this.btnExport.CanFocus = true;
			this.btnExport.Name = "btnExport";
			this.btnExport.UseUnderline = true;
			this.btnExport.Label = global::Mono.Unix.Catalog.GetString ("Export Header");
			this.hbox2.Add (this.btnExport);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnExport]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnPartClose = new global::Gtk.Button ();
			this.btnPartClose.CanFocus = true;
			this.btnPartClose.Name = "btnPartClose";
			this.btnPartClose.UseUnderline = true;
			this.btnPartClose.Label = global::Mono.Unix.Catalog.GetString ("Close Window");
			this.hbox2.Add (this.btnPartClose);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnPartClose]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.treePartition.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreePartitionRowActivated);
			this.txtRAM.Changed += new global::System.EventHandler (this.OnTxtRAMChanged);
			this.txtFile.Changed += new global::System.EventHandler (this.OnTxtFileChanged);
			this.btnExport.Clicked += new global::System.EventHandler (this.OnBtnExportClicked);
			this.btnPartClose.Clicked += new global::System.EventHandler (this.OnBtnPartCloseClicked);
		}
	}
}
